# Generated by Django 4.1.3 on 2023-02-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bid_start_price',
            field=models.IntegerField(),
        ),
    ]
