# Generated by Django 4.1.3 on 2023-02-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auction_details_registration_onsale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onsale',
            name='bid_gap',
        ),
        migrations.AddField(
            model_name='auction_details',
            name='auction_on',
            field=models.BooleanField(default=False),
        ),
    ]
